# Generated by Django 6.1.1 on 2026-09-07 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for players'), ('BIDDING', 'Bidding'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished')], default='WAITING', max_length=20)),
                ('dealer_restriction', models.BooleanField(default=True)),
                ('round_mode', models.CharField(default='UP_DOWN', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('seat', models.PositiveSmallIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('tricks_won', models.PositiveSmallIntegerField(default=0)),
                ('is_dealer', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
            options={
                'ordering': ['seat'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('cards_per_player', models.PositiveSmallIntegerField()),
                ('trump_suit', models.CharField(choices=[('SPADES', 'Spades'), ('DIAMONDS', 'Diamonds'), ('CLUBS', 'Clubs'), ('HEARTS', 'Hearts')], max_length=10)),
                ('status', models.CharField(choices=[('DEALING', 'Dealing'), ('BIDDING', 'Bidding'), ('PLAYING', 'Playing'), ('COMPLETE', 'Complete')], default='DEALING', max_length=20)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='game.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_rounds', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('SPADES', 'Spades'), ('DIAMONDS', 'Diamonds'), ('CLUBS', 'Clubs'), ('HEARTS', 'Hearts')], max_length=10)),
                ('rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King'), ('A', 'Ace')], max_length=2)),
                ('is_played', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.round')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.round')),
            ],
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('lead_suit', models.CharField(blank=True, choices=[('SPADES', 'Spades'), ('DIAMONDS', 'Diamonds'), ('CLUBS', 'Clubs'), ('HEARTS', 'Hearts')], max_length=10)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_tricks', to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='game.round')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tricks', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.player')),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='game.trick')),
            ],
            options={
                'ordering': ['played_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'seat'), name='unique_game_seat'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='unique_game_round'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('round', 'suit', 'rank'), name='unique_round_card'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='unique_round_bid'),
        ),
        migrations.AddConstraint(
            model_name='trick',
            constraint=models.UniqueConstraint(fields=('round', 'number'), name='unique_round_trick'),
        ),
        migrations.AddConstraint(
            model_name='playedcard',
            constraint=models.UniqueConstraint(fields=('trick', 'player'), name='one_card_per_player_trick'),
        ),
    ]
