# Generated by Django 5.1.3 on 2026-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_deck_count_alter_bid_id_alter_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120),
        ),
    ]
