# Generated by Django 5.1.3 on 2026-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_userreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='actual_tricks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
